export default function CountryOptions() {
    return (
        <>
            <option value="Австралия">Австралия</option>
            <option value="Австрия">Австрия</option>
            <option value="Азербайджан">Азербайджан</option>
            <option value="Албания">Албания</option>
            <option value="Алжир">Алжир</option>
            <option value="Американска Самоа">Американска Самоа</option>
            <option value="Американски Вирджински острови">Американски Вирджински острови</option>
            <option value="Ангила">Ангила</option>
            <option value="Ангола">Ангола</option>
            <option value="Андора">Андора</option>
            <option value="Антигуа">Антигуа</option>
            <option value="Аржентина">Аржентина</option>
            <option value="Армения">Армения</option>
            <option value="Аруба">Аруба</option>
            <option value="Афганистан">Афганистан</option>
            <option value="Бангладеш">Бангладеш</option>
            <option value="Барбадос">Барбадос</option>
            <option value="Бахами">Бахами</option>
            <option value="Бахрейн">Бахрейн</option>
            <option value="Беларус">Беларус</option>
            <option value="Белгия">Белгия</option>
            <option value="Белиз">Белиз</option>
            <option value="Бенин">Бенин</option>
            <option value="Бермуда">Бермуда</option>
            <option value="Боливия">Боливия</option>
            <option value="Босна и Херцеговина">Босна и Херцеговина</option>
            <option value="Ботсвана">Ботсвана</option>
            <option value="Бразилия">Бразилия</option>
            <option value="Британска индоокеанска територия">Британска индоокеанска територия</option>
            <option value="Британски Вирджински острови">Британски Вирджински острови</option>
            <option value="Бруней">Бруней</option>
            <option value="Буркина Фасо">Буркина Фасо</option>
            <option value="Бурунди">Бурунди</option>
            <option value="Бутан">Бутан</option>
            <option value="България">България</option>
            <option value="Вануату">Вануату</option>
            <option value="Ватикана">Ватикана</option>
            <option value="Великобритания">Великобритания</option>
            <option value="Венецуела">Венецуела</option>
            <option value="Виетнам">Виетнам</option>
            <option value="Габон">Габон</option>
            <option value="Гамбия">Гамбия</option>
            <option value="Гана">Гана</option>
            <option value="Гваделупа">Гваделупа</option>
            <option value="Гватемала">Гватемала</option>
            <option value="Гвиана">Гвиана</option>
            <option value="Гвинея">Гвинея</option>
            <option value="Гвинея-Бисау">Гвинея-Бисау</option>
            <option value="Германия">Германия</option>
            <option value="Гибралтар">Гибралтар</option>
            <option value="Гренада">Гренада</option>
            <option value="Гренландия">Гренландия</option>
            <option value="Грузия">Грузия</option>
            <option value="Гуам">Гуам</option >
            <option value="Гърция">Гърция</option>
            <option value="Дания">Дания</option>
            <option value="Демократична република Конго">Демократична република Конго</option>
            <option value="Джибути">Джибути</option>
            <option value="Джърси">Джърси</option>
            <option value="Доминика">Доминика</option>
            <option value="Доминиканска република">Доминиканска република</option>
            <option value="Египет">Египет</option>
            <option value="Еквадор">Еквадор</option>
            <option value="Екваториална Гвинея">Екваториална Гвинея</option>
            <option value="Ел Салвадор">Ел Салвадор</option>
            <option value="Еритрея">Еритрея</option>
            <option value="Есватини">Есватини</option>
            <option value="Естония">Естония</option>
            <option value="Етиопия">Етиопия</option>
            <option value="Замбия">Замбия</option>
            <option value="Западна Сахара">Западна Сахара</option>
            <option value="Зимбабве">Зимбабве</option>
            <option value="Израел">Израел</option>
            <option value="Източен Тимор">Източен Тимор</option>
            <option value="Индия">Индия</option>
            <option value="Индонезия">Индонезия</option>
            <option value="Ирак">Ирак</option >
            <option value="Иран">Иран</option >
            <option value="Ирландия">Ирландия</option>
            <option value="Исландия">Исландия</option>
            <option value="Испания">Испания</option>
            <option value="Италия">Италия</option>
            <option value="Йемен">Йемен</option>
            <option value="Йордания">Йордания</option>
            <option value="Кабо Верде">Кабо Верде</option>
            <option value="Казахстан">Казахстан</option>
            <option value="Кайманови острови">Кайманови острови</option>
            <option value="Камбоджа">Камбоджа</option>
            <option value="Камерун">Камерун</option>
            <option value="Канада">Канада</option>
            <option value="Катар">Катар</option>
            <option value="Кения">Кения</option>
            <option value="Кипър">Кипър</option>
            <option value="Киргизстан">Киргизстан</option>
            <option value="Кирибати">Кирибати</option>
            <option value="Китай">Китай</option>
            <option value="Кокосови острови/ Острови Килинг">Кокосови острови/ Острови Килинг</option>
            <option value="Колумбия">Колумбия</option>
            <option value="Коморски острови/ Коморски съюз">Коморски острови/ Коморски съюз</option>
            <option value="Конго">Конго</option>
            <option value="Косово">Косово</option>
            <option value="Коста Рика">Коста Рика</option>
            <option value="Кот д'Ивоар/ Бряг на слоновата кост">Кот д'Ивоар/ Бряг на слоновата кост</option>
            <option value="Куба">Куба</option >
            <option value="Кувейт">Кувейт</option>
            <option value="Кюрасао">Кюрасао</option>
            <option value="Лаос">Лаос</option >
            <option value="Латвия">Латвия</option>
            <option value="Лесото">Лесото</option>
            <option value="Либерия">Либерия</option>
            <option value="Либия">Либия</option>
            <option value="Ливан">Ливан</option>
            <option value="Литва">Литва</option>
            <option value="Лихтенщайн">Лихтенщайн</option>
            <option value="Люксембург">Люксембург</option>
            <option value="Мавритания">Мавритания</option>
            <option value="Мавриций">Мавриций</option>
            <option value="Мадагаскар">Мадагаскар</option>
            <option value="Майот">Майот</option>
            <option value="Макао">Макао</option>
            <option value="Малави">Малави</option>
            <option value="Малайзия">Малайзия</option>
            <option value="Малдиви">Малдиви</option>
            <option value="Мали">Мали</option >
            <option value="Малки далечни острови – САЩ">Малки далечни острови – САЩ</option>
            <option value="Малта">Малта</option>
            <option value="Мароко">Мароко</option>
            <option value="Мартиника">Мартиника</option>
            <option value="Маршалови острови">Маршалови острови</option>
            <option value="Мексико">Мексико</option>
            <option value="Мианмар">Мианмар</option>
            <option value="Микронезия">Микронезия</option>
            <option value="Мозамбик">Мозамбик</option>
            <option value="Молдова">Молдова</option>
            <option value="Монако">Монако</option>
            <option value="Монголия">Монголия</option>
            <option value="Монсерат">Монсерат</option>
            <option value="Намибия">Намибия</option>
            <option value="Науру">Науру</option>
            <option value="Непал">Непал</option>
            <option value="Нигер">Нигер</option>
            <option value="Нигерия">Нигерия</option>
            <option value="Нидерландски антили">Нидерландски антили</option>
            <option value="Никарагуа">Никарагуа</option>
            <option value="Ниуе">Ниуе</option >
            <option value="Нова Зеландия">Нова Зеландия</option>
            <option value="Нова Каледония">Нова Каледония</option>
            <option value="Норвегия">Норвегия</option>
            <option value="Норфолкски остров">Норфолкски остров</option>
            <option value="о-в Света Елена">о-в Света Елена</option>
            <option value="о-в Свети Вартоломей">о-в Свети Вартоломей</option>
            <option value="Обединени Арабски Емирства/ ОАЕ">Обединени Арабски Емирства/ ОАЕ</option>
            <option value="Оландски острови">Оландски острови</option>
            <option value="Оман">Оман</option >
            <option value="Остров Ман">Остров Ман</option>
            <option value="Остров Рождество/ Коледен остров">Остров Рождество/ Коледен остров</option>
            <option value="Острови Кук">Острови Кук</option>
            <option value="Острови Питкерн">Острови Питкерн</option>
            <option value="Острови Търкс и Кайкос">Острови Търкс и Кайкос</option>
            <option value="Пакистан">Пакистан</option>
            <option value="Палау">Палау</option>
            <option value="Палестина">Палестина</option>
            <option value="Панама">Панама</option>
            <option value="Папуа Нова Гвинея">Папуа Нова Гвинея</option>
            <option value="Парагвай">Парагвай</option>
            <option value="Перу">Перу</option >
            <option value="Полша">Полша</option>
            <option value="Португалия">Португалия</option>
            <option value="Пуерто Рико">Пуерто Рико</option>
            <option value="Реюнион">Реюнион</option>
            <option value="Руанда">Руанда</option>
            <option value="Румъния">Румъния</option>
            <option value="Русия">Русия</option>
            <option value="Самоа">Самоа</option>
            <option value="Сан Марино">Сан Марино</option>
            <option value="Санта Лучия">Санта Лучия</option>
            <option value="Сао Томе и Принсипи">Сао Томе и Принсипи</option>
            <option value="Саудитска Арабия">Саудитска Арабия</option>
            <option value="САЩ">САЩ</option >
            <option value="Северна Корея">Северна Корея</option>
            <option value="Северна Македония">Северна Македония</option>
            <option value="Северни Мариански острови">Северни Мариански острови</option>
            <option value="Сейнт Винсент и Гренадини">Сейнт Винсент и Гренадини</option>
            <option value="Сейнт Китс и Невис">Сейнт Китс и Невис</option>
            <option value="Сейшели">Сейшели</option>
            <option value="Сен Мартен (френска част)">Сен Мартен (френска част)</option>
            <option value="Сен Пиер и Микелон">Сен Пиер и Микелон</option>
            <option value="Сенегал">Сенегал</option>
            <option value="Сиера Леоне">Сиера Леоне</option>
            <option value="Сингапур">Сингапур</option>
            <option value="Синт Мартен">Синт Мартен</option>
            <option value="Сирия">Сирия</option>
            <option value="Словакия">Словакия</option>
            <option value="Словения">Словения</option>
            <option value="Соломонови острови">Соломонови острови</option>
            <option value="Сомалия">Сомалия</option>
            <option value="Судан">Судан</option>
            <option value="Суринам">Суринам</option>
            <option value="Сърбия">Сърбия</option>
            <option value="Таджикистан">Таджикистан</option>
            <option value="Тайван">Тайван</option>
            <option value="Тайланд">Тайланд</option>
            <option value="Танзания">Танзания</option>
            <option value="Того">Того</option >
            <option value="Токелау">Токелау</option>
            <option value="Тонга">Тонга</option>
            <option value="Тринидад и Тобаго">Тринидад и Тобаго</option>
            <option value="Тувалу">Тувалу</option>
            <option value="Тунис">Тунис</option>
            <option value="Туркменистан">Туркменистан</option>
            <option value="Турция">Турция</option>
            <option value="Уганда">Уганда</option>
            <option value="Узбекистан">Узбекистан</option>
            <option value="Украйна">Украйна</option>
            <option value="Унгария">Унгария</option>
            <option value="Уолис и Футуна">Уолис и Футуна</option>
            <option value="Уругвай">Уругвай</option>
            <option value="Фарьорски острови">Фарьорски острови</option>
            <option value="Фиджи">Фиджи</option>
            <option value="Филипини">Филипини</option>
            <option value="Финландия">Финландия</option>
            <option value="Фолкландски острови">Фолкландски острови</option>
            <option value="Франция">Франция</option>
            <option value="Френска Гвиана">Френска Гвиана</option>
            <option value="Френска Полинезия">Френска Полинезия</option>
            <option value="Хаити">Хаити</option>
            <option value="Холандия">Холандия</option>
            <option value="Хонг Конг">Хонг Конг</option>
            <option value="Хондурас">Хондурас</option>
            <option value="Хърватия">Хърватия</option>
            <option value="Централноафриканска република/ ЦАР">Централноафриканска република/ ЦАР</option>
            <option value="Чад">Чад</option >
            <option value="Черна гора">Черна гора</option>
            <option value="Чехия">Чехия</option>
            <option value="Чили">Чили</option >
            <option value="Швейцария">Швейцария</option>
            <option value="Швеция">Швеция</option>
            <option value="Шри Ланка">Шри Ланка</option>
            <option value="Южен Судан">Южен Судан</option>
            <option value="Южна Джорджия и Южни сандвичеви острови">Южна Джорджия и Южни сандвичеви острови</option>
            <option value="Южна Корея">Южна Корея</option>
            <option value="Южноафриканска република/ ЮАР">Южноафриканска република/ ЮАР</option>
            <option value="Ямайка">Ямайка</option>
            <option value="Япония">Япония</option>
        </>
    )
}